### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by matiasdelellis** [HuayraLinux/arduino-installer#1]
- [ ] Chequear suma de comprobacion.
- [ ] Comprobar version antes de proceder.
- [ ] Permisos para manejar puerto.
- [ ] Reutilizar iconos oficiales y chequear licencias..
